### ISSUE TITLE
[BUG] Extreamly slow charging speed

### ISSUE THREAD

**Issue by ErrorxCode** [Atom-X-Devs/android_kernel_xiaomi_sm7325#10]
Using this kernel only gets me 12-15W max out of 67. While other kernels are charging at 30-50W. Why is it so?

**Comment by Divyanshu-Modi** [comment]
It's something with the blobs new blobs may require different set of changes the rom I use has proper working

**Comment by ErrorxCode** [comment]
What rom are you using? and do you know how can I use stock kernel with custom ROMs (if it fix the slow charging problem) ?

**Comment by Divyanshu-Modi** [comment]
@ErrorxCode Aospa and stock won't help alot

**Comment by ErrorxCode** [comment]
Rising OS for redwood provides up to 30-35W. Don't know which kernel they are using but any other rom which is using AtomX kernel is charging at 0.5A (2W).

Do you know any other AOSP custom rom that can at least support half the charging speed if not full?

**Comment by ErrorxCode** [comment]
Solved : For fast charging to work, the screen must be completely off along with all other stuffs
