### ISSUE TITLE
Last build r4 1655 

### ISSUE THREAD

**Issue by rotvaldi** [Atom-X-Devs/android_kernel_xiaomi_sm7325#2]
Everytime I restart the phone the recovery fails or doesnt turn on, I must restart again 2 or 3 times and it works.

Pixel OS last A12 build
Magisk 12.5
Pixel OS recovery
13.0.5 firmware update
Xiaomi Lite 11 5G NE 8gb/256gb

**Comment by kardebayan** [comment]
@hadewych skill issue

**Comment by Divyanshu-Modi** [comment]
> Everytime I restart the phone the recovery fails or doesnt turn on, I must restart again 2 or 3 times and it works.
> 
> Pixel OS last A12 build Magisk 12.5 Pixel OS recovery 13.0.5 firmware update Xiaomi Lite 11 5G NE 8gb/256gb

ok thx for testing will have a look

**Comment by Tashar02** [comment]
@hadewych Lmao
