### ISSUE TITLE
Add KernelSU

### ISSUE THREAD

**Issue by assasukasse** [Atom-X-Devs/android_kernel_xiaomi_sm7325#7]
Not really an issue or a bug, yet I was wondering if it would be possible to add the KernelSU to this kernel.
I am currently using a note 8 with kernelSU and it works wonderfully, the SU being completely hidden from unauthorised apks.
I do not have the necessary knowledge to do myself (i do not even know how to compile the kernel)..
Thanks

**Comment by Divyanshu-Modi** [comment]
@assasukasse Never :)
