### ISSUE TITLE
Can't compile kernel using WeebX-Clang 18

### ISSUE THREAD

**Issue by ComradeWave** [Atom-X-Devs/android_kernel_xiaomi_sm7325#8]
When compiling xiaomi_stock_defconfig this error arises:
`
Error: ../arch/arm64/boot/dts/vendor/qcom/shima-gpu.dtsi:88.3-53 Properties must precede subnodes
FATAL ERROR: Unable to parse input tree
make[4]: *** [scripts/Makefile.lib:305: arch/arm64/boot/dts/vendor/qcom/shima-rumi.dtb] Error 1
make[3]: *** [../scripts/Makefile.build:556: arch/arm64/boot/dts/vendor/qcom] Error 2
make[2]: *** [../scripts/Makefile.build:556: arch/arm64/boot/dts/vendor] Error 2
make[1]: *** [/home/wave/android_kernel_xiaomi_sm7325/Makefile:1386: dtbs] Error 2
make[1]: *** Waiting for unfinished jobs....
`

**Comment by Tashar02** [comment]
> When compiling xiaomi_stock_defconfig this error arises: `Error: ../arch/arm64/boot/dts/vendor/qcom/shima-gpu.dtsi:88.3-53 Properties must precede subnodes FATAL ERROR: Unable to parse input tree make[4]: *** [scripts/Makefile.lib:305: arch/arm64/boot/dts/vendor/qcom/shima-rumi.dtb] Error 1 make[3]: *** [../scripts/Makefile.build:556: arch/arm64/boot/dts/vendor/qcom] Error 2 make[2]: *** [../scripts/Makefile.build:556: arch/arm64/boot/dts/vendor] Error 2 make[1]: *** [/home/wave/android_kernel_xiaomi_sm7325/Makefile:1386: dtbs] Error 2 make[1]: *** Waiting for unfinished jobs....`

You are supposed to combine your necessary *-fragment.config into xiaomi-qgki_defconfig and use it for compilation.

**Comment by ComradeWave** [comment]
> > When compiling xiaomi_stock_defconfig this error arises: `Error: ../arch/arm64/boot/dts/vendor/qcom/shima-gpu.dtsi:88.3-53 Properties must precede subnodes FATAL ERROR: Unable to parse input tree make[4]: *** [scripts/Makefile.lib:305: arch/arm64/boot/dts/vendor/qcom/shima-rumi.dtb] Error 1 make[3]: *** [../scripts/Makefile.build:556: arch/arm64/boot/dts/vendor/qcom] Error 2 make[2]: *** [../scripts/Makefile.build:556: arch/arm64/boot/dts/vendor] Error 2 make[1]: *** [/home/wave/android_kernel_xiaomi_sm7325/Makefile:1386: dtbs] Error 2 make[1]: *** Waiting for unfinished jobs....`
> 
> You are supposed to combine your necessary *-fragment.config into xiaomi-qgki_defconfig and use it for compilation.

Ah i see, I'll definitely try it once i get some free time, i even tried compiling with gki_defconfig and vendor/redwood-fragment.config, but it gave a similar error.

**Comment by dakkshesh07** [comment]
@ComradeWave Weebx clang
