### ISSUE TITLE
Build fails due to duplicate srcs

### ISSUE THREAD

**Issue by ondrejnedoma** [Atom-X-Devs/android_kernel_xiaomi_sm7325#9]
error: kernel/xiaomi/sm7325/gen_headers_arm64.bp:1054:1: module "qti_generate_kernel_header
s_arm64": multiple locations for label "linux/netfilter_ipv4/ipt_NATTYPE.h": "out/soong/.in
termediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm64/gen/linux/netfilter_ipv4
/ipt_NATTYPE.h" and "out/soong/.intermediates/kernel/xiaomi/sm7325/qti_generate_kernel_head
ers_arm64/gen/linux/netfilter_ipv4/ipt_NATTYPE.h" (do you have duplicate srcs entries?)
#
error: kernel/xiaomi/sm7325/gen_headers_arm64.bp:1054:1: module "qti_generate_kernel_header
s_arm64": multiple locations for label "audio/linux/msm_audio_ar.h": "out/soong/.intermedia
tes/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm64/gen/audio/linux/msm_audio_ar.h" 
and "out/soong/.intermediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm64/gen/au
dio/linux/msm_audio_ar.h" (do you have duplicate srcs entries?)
#
error: kernel/xiaomi/sm7325/gen_headers_arm64.bp:1054:1: module "qti_generate_kernel_header
s_arm64": multiple locations for label "linux/eavb_shared.h": "out/soong/.intermediates/ker
nel/xiaomi/sm7325/qti_generate_kernel_headers_arm64/gen/linux/eavb_shared.h" and "out/soong
/.intermediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm64/gen/linux/eavb_share
d.h" (do you have duplicate srcs entries?)
#
error: kernel/xiaomi/sm7325/gen_headers_arm.bp:1059:1: module "qti_generate_kernel_headers_
arm": multiple locations for label "linux/netfilter_ipv4/ipt_NATTYPE.h": "out/soong/.interm
ediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm/gen/linux/netfilter_ipv4/ipt_N
ATTYPE.h" and "out/soong/.intermediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_ar
m/gen/linux/netfilter_ipv4/ipt_NATTYPE.h" (do you have duplicate srcs entries?)
#
error: kernel/xiaomi/sm7325/gen_headers_arm.bp:1059:1: module "qti_generate_kernel_headers_
arm": multiple locations for label "linux/netfilter_ipv4/ipt_TRIGGER.h": "out/soong/.interm
ediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm/gen/linux/netfilter_ipv4/ipt_T
RIGGER.h" and "out/soong/.intermediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_ar
m/gen/linux/netfilter_ipv4/ipt_TRIGGER.h" (do you have duplicate srcs entries?)
#
error: kernel/xiaomi/sm7325/gen_headers_arm.bp:1059:1: module "qti_generate_kernel_headers_
arm": multiple locations for label "audio/linux/msm_audio_ar.h": "out/soong/.intermediates/
kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm/gen/audio/linux/msm_audio_ar.h" and "o
ut/soong/.intermediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm/gen/audio/linu
x/msm_audio_ar.h" (do you have duplicate srcs entries?)
#
error: kernel/xiaomi/sm7325/gen_headers_arm.bp:1059:1: module "qti_generate_kernel_headers_
arm": multiple locations for label "linux/eavb_shared.h": "out/soong/.intermediates/kernel/
xiaomi/sm7325/qti_generate_kernel_headers_arm/gen/linux/eavb_shared.h" and "out/soong/.inte
rmediates/kernel/xiaomi/sm7325/qti_generate_kernel_headers_arm/gen/linux/eavb_shared.h" (do
 you have duplicate srcs entries?)

**Comment by TogoFire** [comment]
Simple. Just go to gen_headers_arm.bp and gen_headers_arm64.bp and remove duplicate srcs entries.

Just remove this:
multiple locations for label:  ".........."
linux/netfilter_ipv4/ipt_NATTYPE.h
audio/linux/msm_audio_ar.h
linux/eavb_shared.h
inux/netfilter_ipv4/ipt_TRIGGER.h
audio/linux/msm_audio_ar.h
linux/eavb_shared.h

Idea for commit name:
gen_headers*: Fix duplicate srcs entries
